3d mapper
ugsfume/gra pull request #23
Opened 2024-04-12 17:09 UTC by ugsfume

This build completes the cone mapping function in the software pipeline (without SLAM)
General Software Pipeline: Perception -> Cone Recognition + Cluster Detection -> Cone Mapping -> SLAM (optional for simulation) ->  Path Planning -> Path Follower

Major Features:

- Transform cone poses from tracker node to be directly associated with the global frame. 
- Append newly detected cones to an array, input to the path planning algorithm
- Allow GPU acceleration for object recognition

Minor Features:

- Created friendly workspace for gazebo world building
- Detected cone visualisation
- Launch files for grouping cone mapping nodes

Mapping Visualised:
![Screenshot from 2024-04-12 17-30-24](https://github.com/ugsfume/gra/assets/86786290/74fa1e64-6bbc-4d28-80c9-2922875bb005)

Node Graph:
![Screenshot from 2024-04-12 17-30-24](https://github.com/ugsfume/gra/assets/86786290/636e5594-05ce-48f7-9548-38c9ebafd4f1)

Instructions:

1. Go to docker-compose.yml to enable/disable GPU option
2. Rebuild Docker
3. roscore
4. roslaunch ackermann_vehicle_description hokuyo_odom.launch
5. roslaunch ultralytics_ros tracker_with_cloud.launch
6. roslaunch ultralytics_ros cone_mapper.launch
7. roslaunch ackermann_vehicle_navigation path_follower.launch

TODO:

- Incorporate path planning algorithm into the software pipeline (WIP based on this build)
- Implement SLAM
- Define mission specific behaviours
- Complete hardware build
- Adjust to hardware specific conditions (odometry, HardwareInterface, Linux and Nvidia environment setup)

2024-04-15 00:04 UTC, daniel-bara requested changes

2024-04-15 00:07 UTC, ugsfume commented on .devcontainer/docker-compose.yml
> +      - /dev/ttyACM0:/dev/ttyACM0
No, but it just leaves the port open in case we use an embedded board

2024-04-15 00:08 UTC, ugsfume commented on README.md
Just an empty line I guess? I think I might have made some modification to README.md at some point but reverted afterwards.

2024-04-15 00:10 UTC, ugsfume commented on cones2.xml
This is a map that contain cones sparsely spaced to test the perception transformation algo

2024-04-15 00:14 UTC, ugsfume commented on ros/ackermann_vehicle_gazebo/worlds/gazebo_world_building/boloyb.world
World that contains blue, orange, large orange, yellow, and blue cones. Again, it was used to test the perception transformation pipeline. Can be deleted or renamed.

2024-04-15 00:15 UTC, ugsfume commented on ros/ackermann_vehicle_navigation/path/npz_script
No, they corresepond to the coordinates relative to the global anchoring frame /world.

2024-04-15 00:18 UTC, ugsfume commented on cones2.xml
I am removing this file since this is no longer needed and that I have since created a few more worlds that do the equivalent.

2024-04-15 00:21 UTC, ugsfume commented on ros/ackermann_vehicle_navigation/path/npz_script
> +# Correct the rotation and add 1 to the x-coordinate after rotation
That was an outdated comment, I have since moved the spawn point of the vehicle to [0,0] so this comment so longer applies.

2024-04-15 00:25 UTC, ugsfume commented on ros/ackermann_vehicle_navigation/scripts/tf_odom_publisher.py
> -    t.transform.translation.x = msg.pose[vehicle_index].position.x + 1
My guess is that for the original application the car does not spawn at the origin, so they added the offset in the odom messages. This is no longer needed as our simulator spawns car at the origin to not complicate things.

2024-04-16 13:46 UTC, daniel-bara requested changes

2024-04-16 13:46 UTC, daniel-bara commented on gazebo_world_building/Instructions.txt
> +1. run 'rosrus gazebo_ros gazebo' to launch an empty world
```suggestion
1. run 'rosrun gazebo_ros gazebo' to launch an empty world
```

2024-04-16 13:46 UTC, daniel-bara commented on gazebo_world_building/Instructions.txt
> +6. Go into the world file, and change all fields of uri to be absolute paths (Use Change all occurances in VScode)
```suggestion
6. Go into the world file, and change all fields of uri to be absolute paths (Use Change all occurrences in VScode)
```

2024-04-16 22:10 UTC, daniel-bara approved these changes

2024-04-16 22:38 UTC, merged